name: juxta-repo-clear

on:
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Remove repository directory
        run: |
          if [ -d repository ] && ! [ -L repository ]; then
            rm -rf repository
          else
            echo "Safety check failed: repository must exist and not be a symlink."
            exit 1
          fi

      - name: Commit removal
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "✨ No repository directory to remove"
          else
            git commit -m "Remove repository directory"
            git push
          fi

