name: juxta-repo-cleanup
# Replaces README.md with SETTINGS.md
# and removes LICENSE.md, juxta-repo.jpg and repository/

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rename SETTINGS.md to README.md
        run: |
          if [ -f SETTINGS.md ]; then
            [ -f README.md ] && mv README.md HELP.md
            mv SETTINGS.md README.md
          fi

      - name: Delete LICENSE.md and logo
        run: |
          rm -f LICENSE.md juxta-repo.jpg

      - name: Remove repository directory
        run: |
          rm -rf repository

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Update README.md from SETTINGS.md" \
            || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
